---
- hosts: localhost
  roles:
     - { role: ansiblebit.oracle-java,
         oracle_java_set_as_default: yes }
     - jdauphant.intellij
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list
  tasks:
    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        backup: yes
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      tags:
        - config

    - name: Add Google Chrome key
      apt_key:
        url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
        state: present
      tags:
        - config

    - name: Add Google Chrome repo
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: 'google-chrome'
      tags:
        - config

    - name: Add Atlassian key
      apt_key:
        url: "https://atlassian.artifactoryonline.com/atlassian/api/gpg/key/public"
        state: present
      tags:
        - config

    - name: Add Atlassian Hipchat repo
      apt_repository:
        repo: deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client xenial main
        state: present
      tags:
        - config

    - name: Add WineHQ repo
      apt_repository:
        repo: 'ppa:wine/wine-builds'
        state: present
      tags:
        - config

    - name: Install Debian packages
      apt:
        name: "{{item}}"
        state: installed
        update_cache: yes
      with_items:
        - git
        - google-chrome-stable
        - hipchat4
        - jq
        - python-pip
        - sshuttle
        - terminator
        - vagrant
        - virtualbox-qt
        - vim
        - wine
      tags:
        - patch

    - name: Install Pip packages
      pip:
        name: "{{ item }}"
      with_items:
        - ansible-lint
      tags:
        - patch

    - name: Create high level scratch directory
      file:
        path: /scratch
        state: directory
        mode: 0755
      tags:
        - config

    - name: Create scratch directory for users
      file:
        path: "/scratch/{{ item }}"
        owner: "{{ item }}"
        group: "{{ item }}"
        state: directory
        mode: 0700
      with_items:
        - ben
      tags:
        - config