---
# Author: Ben =D=
# Description: Install a Xenial workstation
#
# Examples:
#  ```ansible-galaxy install -r roles/roles.yml
#  ansible-playbook ben-SATELLITE-P50-C.yml --ask-sudo-pass```
- hosts: localhost
  roles:
     - { role: ansiblebit.oracle-java,
         oracle_java_set_as_default: yes }
     - jdauphant.intellij
  tasks:
    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        backup: yes
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      tags:
        - config

    - name: Add Docker Key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
      tags:
        - config

    - name: Add Docker repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
        state: present
      tags:
        - config

    - name: Add Google Chrome key
      apt_key:
        url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
        state: present
      tags:
        - config

    - name: Add Google Chrome repo
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: 'google-chrome'
      tags:
        - config

    - name: Add Atlassian key
      apt_key:
        url: "https://atlassian.artifactoryonline.com/atlassian/api/gpg/key/public"
        state: present
      tags:
        - config

    - name: Add Atlassian Hipchat repo
      apt_repository:
        repo: deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client xenial main
        state: present
      tags:
        - config

    - name: Add WineHQ repo
      apt_repository:
        repo: 'ppa:wine/wine-builds'
        state: present
      tags:
        - config

    # Install a collection of packages.
    - name: Install Debian packages
      apt:
        name: "{{item}}"
        state: installed
        update_cache: yes
      with_items:
        - cowsay
        - docker-ce
        - git
        - google-chrome-stable
        - hipchat4
        - jq
        - nmap
        - pep8
        - pep257
        - python-gpgme
        - python-pip
        - sshuttle
        - terminator
        - vagrant
        - virtualbox-qt
        - vim
        - wine
      tags:
        - patch

    - name: Install Pip packages
      pip:
        name: "{{ item }}"
      with_items:
        - ansible-docgen
        - ansible-lint
      tags:
        - patch

    - name: Create high level scratch directory
      file:
        path: /scratch
        state: directory
        mode: 0755
      tags:
        - config

    - name: Create scratch directory for users
      file:
        path: "/scratch/{{ item }}"
        owner: "{{ item }}"
        group: "{{ item }}"
        state: directory
        mode: 0700
      with_items:
        - ben
      tags:
        - config

    - name: Ensure ben is a docker
      user:
        name: ben
        groups: docker
        append: yes
      tags:
        - config

    - name: Ensure Docker is enabled and started.
      service:
        name: docker
        state: started
        enabled: yes
      tags:
        - config

    - name: Clear older versions of Idea
      file:
        path: "/opt/intellij/{{ item }}"
        state: absent
      with_items:
        - idea-IC-163.12024.16
      tags:
        - config

    - name: Install ArgoUML
      unarchive:
        creates: '/usr/local/argouml-0.34'
        dest: '/usr/local'
        remote_src: yes
        src: 'http://argouml-downloads.tigris.org/nonav/argouml-0.34/ArgoUML-0.34.tar.gz'
      tags:
        - patch

    - name: Create Symbolic Links for ArgoUML
      file:
        path: "/usr/local/bin/{{ item }}"
        src: "/usr/local/argouml-0.34/{{ item }}"
        state: link
      with_items:
        - argouml.sh
        - argouml2.sh
      tags:
        - patch

    - name: Check if Atom is installed
      stat:
        path: /usr/bin/atom
      register: atom_binary_exists
      tags:
        - patch
        - atom

    - name: Download and install Atom
      apt:
        deb: 'https://atom.io/download/deb'
      when: atom_binary_exists.stat.exists == False
      tags:
        - patch
        - atom

    - name: Check if DropBox is installed
      stat:
        path: /usr/bin/dropbox
      register: dropbox_binary_exists
      tags:
        - patch
        - dropbox

    - name: Download and install DropBox
      apt:
        deb: 'https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb'
      when: dropbox_binary_exists.stat.exists == False
      tags:
        - patch
        - dropbox
