---
# Author: Ben =D=
# Description: Install a Xenial workstation
#
# Examples:
#  ```ansible-galaxy install -r roles/roles.yml
#  ansible-playbook ben-SATELLITE-P50-C.yml --ask-sudo-pass```
- hosts: localhost
  tasks:
    - name: Show me the data
      debug:
        msg: "{{ vars }}"
