---
name: Create an Artefact

on:
  push:
    branches:
      - workflows
    tags:
      - 0.*

jobs:
  artefact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Show GitHub ref
        run: echo "$GITHUB_REF"

      - name: Dump event JSON
        env:
          EVENT_JSON_FILENAME: ${{ github.event_path }}
        run: cat "$EVENT_JSON_FILENAME"

      - name: Get the Latest Tag
        run: |
          git log
          git tag
          echo ::set-env name=LATEST_TAG::$( git tag )

      - name: Show the Latest Tag
        run: echo The latest tag in the repo is $LATEST_TAG
